export const ADMIN_SETTINGS_GET_REQUEST = "ADMIN_SETTINGS_GET_REQUEST";
export const ADMIN_SETTINGS_GET_SUCCESS = "ADMIN_SETTINGS_GET_SUCCESS";
export const ADMIN_SETTINGS_GET_FAIL = "ADMIN_SETTINGS_GET_FAIL";

export const ADMIN_SETTINGS_UPDATE_REQUEST = "ADMIN_SETTINGS_UPDATE_REQUEST";
export const ADMIN_SETTINGS_UPDATE_SUCCESS = "ADMIN_SETTINGS_UPDATE_SUCCESS";
export const ADMIN_SETTINGS_UPDATE_FAIL = "ADMIN_SETTINGS_UPDATE_FAIL";
