export const NARRATIVE_LIST_REQUEST = "NARRATIVE_LIST_REQUEST";
export const NARRATIVE_LIST_SUCCESS = "NARRATIVE_LIST_SUCCESS";
export const NARRATIVE_LIST_FAIL = "NARRATIVE_LIST_FAIL";

export const NARRATIVE_DETAILS_REQUEST = "NARRATIVE_DETAILS_REQUEST";
export const NARRATIVE_DETAILS_SUCCESS = "NARRATIVE_DETAILS_SUCCESS";
export const NARRATIVE_DETAILS_FAIL = "NARRATIVE_DETAILS_FAIL";

export const NARRATIVE_CREATE_REQUEST = "NARRATIVE_CREATE_REQUEST";
export const NARRATIVE_CREATE_SUCCESS = "NARRATIVE_CREATE_SUCCESS";
export const NARRATIVE_CREATE_FAIL = "NARRATIVE_CREATE_FAIL";

export const NARRATIVE_UPDATE_REQUEST = "NARRATIVE_UPDATE_REQUEST";
export const NARRATIVE_UPDATE_SUCCESS = "NARRATIVE_UPDATE_SUCCESS";
export const NARRATIVE_UPDATE_FAIL = "NARRATIVE_UPDATE_FAIL";

export const NARRATIVE_DELETE_REQUEST = "NARRATIVE_DELETE_REQUEST";
export const NARRATIVE_DELETE_SUCCESS = "NARRATIVE_DELETE_SUCCESS";
export const NARRATIVE_DELETE_FAIL = "NARRATIVE_DELETE_FAIL";
