export const PROFILE_GET_REQUEST = "PROFILE_GET_REQUEST";
export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";
export const PROFILE_GET_FAIL = "PROFILE_GET_FAIL";

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";

export const PASSWORD_UPDATE_REQUEST = "PASSWORD_UPDATE_REQUEST";
export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS";
export const PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL";

export const PROFILE_IMAGE_UPDATE_REQUEST = "PROFILE_IMAGE_UPDATE_REQUEST";
export const PROFILE_IMAGE_UPDATE_SUCCESS = "PROFILE_IMAGE_UPDATE_SUCCESS";
export const PROFILE_IMAGE_UPDATE_FAIL = "PROFILE_IMAGE_UPDATE_FAIL";
