export const TELEGRAM_GROUP_CHECK_REQUEST = "TELEGRAM_GROUP_CHECK_REQUEST";
export const TELEGRAM_GROUP_CHECK_SUCCESS = "TELEGRAM_GROUP_CHECK_SUCCESS";
export const TELEGRAM_GROUP_CHECK_FAIL = "TELEGRAM_GROUP_CHECK_FAIL";

export const TELEGRAM_CONNECT_REQUEST = "TELEGRAM_CONNECT_REQUEST";
export const TELEGRAM_CONNECT_SUCCESS = "TELEGRAM_CONNECT_SUCCESS";
export const TELEGRAM_CONNECT_FAIL = "TELEGRAM_CONNECT_FAIL";

export const TELEGRAM_DISCONNECT_REQUEST = "TELEGRAM_DISCONNECT_REQUEST";
export const TELEGRAM_DISCONNECT_SUCCESS = "TELEGRAM_DISCONNECT_SUCCESS";
export const TELEGRAM_DISCONNECT_FAIL = "TELEGRAM_DISCONNECT_FAIL";

export const TELEGRAM_CONNECT_CODE_SENT_TO_PHONE = "TELEGRAM_CONNECT_CODE_SENT_TO_PHONE";

export const TELEGRAM_CONNECT_CODE_INPUT_REQUEST = "TELEGRAM_CONNECT_CODE_INPUT_REQUEST";
export const TELEGRAM_CONNECT_CODE_INPUT_FAIL = "TELEGRAM_CONNECT_CODE_INPUT_FAIL";

export const TELEGRAM_CONNECT_CANCEL = "TELEGRAM_CONNECT_CANCEL";

export const TELEGRAM_SESSION_CHECK_REQUEST = "TELEGRAM_SESSION_CHECK_REQUEST";
export const TELEGRAM_SESSION_CHECK_SUCCESS = "TELEGRAM_SESSION_CHECK_SUCCESS";
export const TELEGRAM_SESSION_CHECK_FAIL = "TELEGRAM_SESSION_CHECK_FAIL";
